services:  
  kafka:
    image: apache/kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"

      # KRaft controller quorum config
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      # Listener config
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092,INTERNAL://kafka:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"

      # Broker internal config
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"


  zookeeper:
    image: zookeeper:3.7
    hostname: zookeeper
    ports:
      - '2181:2181'

  clickhouse1:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: clickhouse1
    environment:
      - CLICKHOUSE_HOST=clickhouse1:9000
      - CLICKHOUSE_USER=default
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
      - ./config/clickhouse1/config.d/config.xml:/etc/clickhouse-server/config.xml
      - ./config/clickhouse1/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ./volume/clickhouse1/data:/var/lib/clickhouse
      - ./volume/clickhouse1/logs:/var/log/clickhouse-server
    ports:
      - '8123:8123'
      - '9000:9000'
    depends_on:
      - zookeeper

  clickhouse2:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: clickhouse2
    environment:
      - CLICKHOUSE_HOST=clickhouse2:9000
      - CLICKHOUSE_USER=default
    volumes:
      - ./config/clickhouse2/config.d/config.xml:/etc/clickhouse-server/config.xml
      - ./config/clickhouse2/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ./volume/clickhouse2/data:/var/lib/clickhouse
      - ./volume/clickhouse2/logs:/var/log/clickhouse-server
    ports:
      - '8124:8123'
      - '9001:9000'
    depends_on:
      - zookeeper

volumes:
  clickhouse1_data:
  clickhouse2_data: